services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: ["/app/docker-entrypoint.sh", "rails", "server", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
